-- ============================================================================
--  MASCOTAS PERDIDAS MISIONES · Actualización 3
--  Agrega: nº de legajo automático + zona/CP en publicaciones
--          + registro de mascotas (con QR) + avistamientos
--  Cómo usarlo: Supabase → SQL Editor → New query → pegar TODO → RUN
--  Es seguro correrlo aunque algo ya exista.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) PUBLICACIONES: nº de legajo correlativo + zona + código postal
-- ---------------------------------------------------------------------------
-- Número de legajo automático (1, 2, 3...). Cada nueva publicación toma el
-- siguiente número solo.
alter table public.publicaciones add column if not exists legajo bigint;

create sequence if not exists public.publicaciones_legajo_seq;

-- Asignar legajo automáticamente al insertar (si no tiene)
create or replace function public.set_legajo()
returns trigger language plpgsql as $$
begin
  if NEW.legajo is null then
    NEW.legajo := nextval('public.publicaciones_legajo_seq');
  end if;
  return NEW;
end $$;

drop trigger if exists trg_set_legajo on public.publicaciones;
create trigger trg_set_legajo
  before insert on public.publicaciones
  for each row execute function public.set_legajo();

-- Poner legajo a las publicaciones viejas que no tengan (por orden de creación)
do $$
declare r record;
begin
  for r in (select id from public.publicaciones where legajo is null order by created_at asc) loop
    update public.publicaciones set legajo = nextval('public.publicaciones_legajo_seq') where id = r.id;
  end loop;
end $$;

-- Nuevas columnas de ubicación
alter table public.publicaciones add column if not exists zona text;
alter table public.publicaciones add column if not exists cp text;


-- ---------------------------------------------------------------------------
-- 2) TABLA: mascotas  (registro preventivo con QR)
-- ---------------------------------------------------------------------------
create table if not exists public.mascotas (
  id         bigint generated by default as identity primary key,
  owner_id   uuid references auth.users(id) on delete set null,
  codigo     text unique not null,
  pet_name   text,
  species    text,
  sex        text,
  color      text,
  features   text,
  zona       text,
  phone      text,
  whatsapp   text,
  photo      text,
  notas      text,
  created_at timestamptz not null default now()
);

alter table public.mascotas enable row level security;

-- Cualquiera puede VER una mascota (necesario para que el QR abra su ficha).
drop policy if exists mascotas_select_todos on public.mascotas;
create policy mascotas_select_todos
  on public.mascotas for select
  to anon, authenticated
  using ( true );

-- Un usuario registrado puede CREAR sus mascotas.
drop policy if exists mascotas_insert_auth on public.mascotas;
create policy mascotas_insert_auth
  on public.mascotas for insert
  to authenticated
  with check ( auth.uid() = owner_id or owner_id is null );

-- El dueño (o la admin) puede EDITAR/BORRAR sus mascotas.
drop policy if exists mascotas_update_owner on public.mascotas;
create policy mascotas_update_owner
  on public.mascotas for update
  to authenticated
  using ( auth.uid() = owner_id or auth.jwt() ->> 'email' = 'lili.kos28@gmail.com' );

drop policy if exists mascotas_delete_owner on public.mascotas;
create policy mascotas_delete_owner
  on public.mascotas for delete
  to authenticated
  using ( auth.uid() = owner_id or auth.jwt() ->> 'email' = 'lili.kos28@gmail.com' );


-- ---------------------------------------------------------------------------
-- 3) TABLA: avistamientos  (avisos de quien escanea un QR)
-- ---------------------------------------------------------------------------
create table if not exists public.avistamientos (
  id             bigint generated by default as identity primary key,
  mascota_id     bigint,
  mascota_codigo text,
  mascota_nombre text,
  owner_id       uuid,
  quien          text,
  contacto       text,
  zona           text,
  nota           text,
  created_at     timestamptz not null default now()
);

alter table public.avistamientos enable row level security;

-- Cualquiera puede DEJAR un aviso (aunque no tenga cuenta).
drop policy if exists avist_insert_todos on public.avistamientos;
create policy avist_insert_todos
  on public.avistamientos for insert
  to anon, authenticated
  with check ( true );

-- El dueño de la mascota o la admin pueden VER los avisos.
drop policy if exists avist_select_owner on public.avistamientos;
create policy avist_select_owner
  on public.avistamientos for select
  to authenticated
  using ( auth.uid() = owner_id or auth.jwt() ->> 'email' = 'lili.kos28@gmail.com' );

-- El dueño o la admin pueden BORRAR avisos.
drop policy if exists avist_delete_owner on public.avistamientos;
create policy avist_delete_owner
  on public.avistamientos for delete
  to authenticated
  using ( auth.uid() = owner_id or auth.jwt() ->> 'email' = 'lili.kos28@gmail.com' );

-- ============================================================================
--  LISTO. Si ves "Success. No rows returned", salió todo bien.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 4) ARREGLO del buzón de Contacto (error 403 que aparecía al enviar)
--    Da permiso explícito al rol público para escribir en las tablas nuevas.
-- ---------------------------------------------------------------------------
grant usage on schema public to anon, authenticated;
grant insert on public.mensajes to anon, authenticated;
grant select, delete on public.mensajes to authenticated;
grant insert on public.avistamientos to anon, authenticated;
grant select, insert, update, delete on public.lugares to authenticated;
grant select on public.lugares to anon;
grant select, insert, update, delete on public.mascotas to authenticated;
grant select on public.mascotas to anon;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Reforzar la política de inserción de mensajes (por si quedó restrictiva)
drop policy if exists mensajes_insert_todos on public.mensajes;
create policy mensajes_insert_todos
  on public.mensajes for insert
  to anon, authenticated
  with check (true);

-- ============================================================================
--  FIN de la actualización 3.
-- ============================================================================

